import Immutable from "immutable";

let emptyList = new Immutable.List();

export default new Immutable.Map({
	"@type": "wwdocument",
	date: "",
	documentType: "Unknown",
	links: emptyList,
	notes: "",
	reference: "",
	"@relations": new Immutable.Map({		// firstEditor: emptyList,
		commentsOnWork: emptyList,
		containedInAnthology: emptyList,
		hasGenre: emptyList,
		hasPublishLocation: emptyList,
		hasWorkLanguage: emptyList,
		hasAdaptation: emptyList,
		hasAnnotationsOn: emptyList,
		hasBibliography: emptyList,
		hasDocumentSource: emptyList,
		hasEdition: emptyList,
		hasSequel: emptyList,
		hasTranslation: emptyList,
		hasPlagiarismBy: emptyList,
		hasPreface: emptyList,
		isCreatedBy: emptyList,
		isAnnotatedIn: emptyList,
		isAdaptationOf: emptyList,
		isAnthologyContaining: emptyList,
		isAwardForWork: emptyList,
		isBibliographyOf: emptyList,
		isCensoredBy: emptyList,
		isCensoringOf: emptyList,
		isCopiedBy: emptyList,
		isCopyOf: emptyList,
		isEditionOf: emptyList,
		isSequelOf: emptyList,
		isPlagiarismOf: emptyList,
		isWorkCommentedOnIn: emptyList,
		isWorkAwarded: emptyList,
		isPrefaceOf: emptyList,
		isIntertextualOf: emptyList,
		isIntertextualTo: emptyList,
		isWorkListedOn: emptyList,
		isWorkMentionedIn: emptyList,
		isParodiedBy: emptyList,
		isParodyOf: emptyList,
		isWorkQuotedIn: emptyList,
		isWorkReferencedIn: emptyList,
		isDocumentSourceOf: emptyList,
		isTranslationOf: emptyList,
		mentionsWork: emptyList,
		listsWork: emptyList,
		quotesWork: emptyList,
		referencesWork: emptyList
	}),
	tempCreator: "",
	tempLanguage: "",
	tempOrigin: "",
	title: ""
});



